services:
  app:
    build:
      target: production
    volumes: []   # remove bind mounts so built assets are used

  # app-ci:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     target: ci
  #   container_name: prepare-a-case-app-ci
  #   networks:
  #     - hmpps
  #   volumes: []