version: '3.1'
services:
  prepare-a-case-redis:
    image: 'bitnami/redis:5.0'
    container_name: prepare-a-case-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
