version: '3.7'
services:

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"
    command: "--global-response-templating --verbose"

networks:
  hmpps:

# you can use hmpps_int but then
# you'll need to use
# http://host.docker.internal:9091/auth/outh/token
# as the token url