minReplicaCount: 1
maxReplicaCount: 1

ingress:
  host: prepare-a-case-dev.apps.live-1.cloud-platform.service.justice.gov.uk

env:
  PAC_ENV: dev
  COURT_CASE_SERVICE_URL: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  NOMIS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  USER_PREFERENCE_SERVICE_URL: https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk
  CASE_SNAPSHOT_TIMES: "00:00,08:45,09:45,10:15,10:45,11:15,11:45,12:15,12:45,13:15,13:45,14:15,14:45,15:15,15:45,16:15,16:45,17:15,17:45"
  CASE_TRACKING_PRE_PILOT_USERS: All
  ENABLE_MOVE_TO_RESULTED_ACTION: true
  ENABLE_WORKFLOW: true
