version: '3.7'
networks:
  hmpps:

services:
  cypress:
    build: 
      context: ..
      dockerfile: ./integration-tests/Dockerfile
    network_mode: host
    environment:
      - CYPRESS_FAIL_FAST_ENABLED=true
      - CYPRESS_CASES_TOTAL_DAYS=${CASES_TOTAL_DAYS:-28}
      - DISPLAY=${DISPLAY}
    working_dir: /e2e
    command: ["run", "-C", "cypress/cypress.config.js"]
    volumes:
      - ../server:/e2e/server
      - ../integration-tests/cypress:/e2e/cypress
      - ../integration-tests/output:/e2e/output

