version: '3.7'
networks:
  hmpps:

services:

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: hmpps-auth
    networks:
      - hmpps
    ports:
      - "9091:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    entrypoint: ["java", "-javaagent:/app/agent.jar", "-jar", "/app/app.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0