# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:
  ingress:
    hosts:
        - prepare-case-probation.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  autoscaling:
    minReplicas: 2
    maxReplicas: 4

  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 100Mi

  env:
    PAC_ENV: prod
    COURT_CASE_SERVICE_URL: https://court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk
    NOMIS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    USER_PREFERENCE_SERVICE_URL: https://hmpps-user-preferences.hmpps.service.justice.gov.uk
    CASE_SNAPSHOT_TIMES: "00:00,08:45,09:45"
    ENABLE_MATCHER_LOGGING: false
    ENABLE_CLICK_ANALYTICS: false

  allowlist:
    groups:
      - moj_cloud_platform
      - digital_staff_and_mojo
      - probation

generic-prometheus-alerts:
    alertSeverity: probation_in_court_alerts_prod